let space1 = "x";
let space2 = "o";
let space3 = " ";
let space4 = "x";
let space5 = "x";
let space6 = " ";
let space7 = "o";
let space8 = " ";
let space9 = " ";
console.log("    |   |   ");
console.log(`  ${space1} | ${space2} |  ${space3} `);
console.log("    |   |   ");
console.log("-------------");
console.log("    |   |   ");
console.log(` ${space4}  | ${space5} |  ${space6} `);
console.log("    |   |   ");
console.log("-------------");
console.log("    |   |   ");
console.log(` ${space7}  |  ${space8}| ${space9} `);
console.log("    |   |   ");
